## Importing libraries

In [1]:
import numpy as np
import pandas as pd

In [2]:
true = pd.read_csv('true.csv')
fake = pd.read_csv('fake.csv')

In [3]:
true

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"
...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017"
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017"
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017"
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017"


In [6]:
fake

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"
...,...,...,...,...
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016"
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016"
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016"
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016"


In [4]:
true['label'] = 0

In [5]:
dataset1 = true[['text', 'label']]

In [7]:
fake['label'] = 1

In [8]:
dataset2 = fake[['text', 'label']]

In [9]:
dataset = pd.concat([dataset1, dataset2])

In [10]:
dataset

,text,label
0,WASHINGTON (Reuters) - The head of a conservat...,0
1,WASHINGTON (Reuters) - Transgender people will...,0
2,WASHINGTON (Reuters) - The special counsel inv...,0
3,WASHINGTON (Reuters) - Trump campaign adviser ...,0
4,SEATTLE/WASHINGTON (Reuters) - President Donal...,0
...,...,...
23476,21st Century Wire says As 21WIRE reported earl...,1
23477,21st Century Wire says It s a familiar theme. ...,1
23478,Patrick Henningsen 21st Century WireRemember ...,1
23479,21st Century Wire says Al Jazeera America will...,1


In [11]:
dataset.shape

(44898, 2)

## Check for null values

In [12]:
dataset.isnull().sum()

text     0
label    0
dtype: int64

In [13]:
dataset['label'].value_counts()

label
1    23481
0    21417
Name: count, dtype: int64

In [14]:
dataset = dataset.sample(frac = 1)

In [15]:
dataset

,text,label
8011,Donald Trump infuriates even the most compassi...,1
18860,AMMAN (Reuters) - Russian and Syrian jets kill...,0
10996,The bipartisan congressional language creates ...,1
10358,News broke a few days ago that there was more ...,1
11394,President Trump visited Michigan to promote th...,1
...,...,...
17092,What happens to Europe if the refugee surge of...,1
3976,Baylor University s vice president for senior ...,1
15732,Another positive step towards restoring our fr...,1
18316,LONDON (Reuters) - Iranian authorities sentenc...,0


# NLP

## Clean

In [16]:
import nltk

In [17]:
import re

In [18]:
from nltk.corpus import stopwords

In [19]:
from nltk.stem import WordNetLemmatizer

In [20]:
ps = WordNetLemmatizer()

In [21]:
stopwords = stopwords.words('english')

In [23]:
dataset['text']

8011     Donald Trump infuriates even the most compassi...
18860    AMMAN (Reuters) - Russian and Syrian jets kill...
10996    The bipartisan congressional language creates ...
10358    News broke a few days ago that there was more ...
11394    President Trump visited Michigan to promote th...
                               ...                        
17092    What happens to Europe if the refugee surge of...
3976     Baylor University s vice president for senior ...
15732    Another positive step towards restoring our fr...
18316    LONDON (Reuters) - Iranian authorities sentenc...
630      WASHINGTON (Reuters) - A report to the U.S. Co...
Name: text, Length: 44898, dtype: object

In [24]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\gayat\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [25]:
def clean_row(row):
    row = row.lower()
    row = re.sub('[^a-zA-Z]',' ',row)
    token = row.split()
    text=(ps.lemmatize(word)for word in token if not word in stopwords)
    cleanned_news = ' '.join(text)
    return cleanned_news

In [26]:
dataset['text']

8011     Donald Trump infuriates even the most compassi...
18860    AMMAN (Reuters) - Russian and Syrian jets kill...
10996    The bipartisan congressional language creates ...
10358    News broke a few days ago that there was more ...
11394    President Trump visited Michigan to promote th...
                               ...                        
17092    What happens to Europe if the refugee surge of...
3976     Baylor University s vice president for senior ...
15732    Another positive step towards restoring our fr...
18316    LONDON (Reuters) - Iranian authorities sentenc...
630      WASHINGTON (Reuters) - A report to the U.S. Co...
Name: text, Length: 44898, dtype: object

In [27]:
dataset['text'] = dataset['text'].apply(lambda x :clean_row(x))

In [28]:
dataset['text']

8011     donald trump infuriates even compassionate hol...
18860    amman reuters russian syrian jet killed least ...
10996    bipartisan congressional language creates head...
10358    news broke day ago reported minor outpatient r...
11394    president trump visited michigan promote auto ...
                               ...                        
17092    happens europe refugee surge mostly muslim men...
3976     baylor university vice president senior operat...
15732    another positive step towards restoring freedo...
18316    london reuters iranian authority sentenced mem...
630      washington reuters report u congress released ...
Name: text, Length: 44898, dtype: object

## encoded

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
import pandas as pd

# Load your data
x = dataset.iloc[:35000, 0]
y = dataset.iloc[:35000, 1]

# Split
train_data, test_data, train_label, test_label = train_test_split(x, y, test_size=0.2, random_state=0)

# Vectorizer
vectorizer = TfidfVectorizer(max_features=50000, lowercase=False, ngram_range=(1, 2))

# Fit only on train
vec_train = vectorizer.fit_transform(train_data)
vec_test = vectorizer.transform(test_data)

# Debug print to verify shape
print("Train shape:", vec_train.shape)
print("Test shape:", vec_test.shape)
print("Feature names length:", len(vectorizer.get_feature_names_out()))

# Convert to DataFrames
training_data = pd.DataFrame(vec_train.toarray(), columns=vectorizer.get_feature_names_out())
testing_data = pd.DataFrame(vec_test.toarray(), columns=vectorizer.get_feature_names_out())


Train shape: (28000, 50000)
Test shape: (7000, 50000)
Feature names length: 50000


In [30]:
vec_train=vec_train.toarray()

In [31]:
vec_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(28000, 50000))

In [32]:
print(vec_train.shape)
print(vectorizer.get_feature_names_out().shape)


(28000, 50000)
(50000,)


In [33]:
training_data

,aa,aadhaar,aapl,aaron,aaron bernstein,aaron burr,aarp,ab,aba,aba aslani,...,zoo,zor,zor city,zor province,zucker,zuckerberg,zuckerberg said,zuma,zurich,zurich reuters
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27996,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27997,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27998,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


# Model

## Naive bayes algorithm

In [34]:
from sklearn.naive_bayes import MultinomialNB

In [35]:
clf = MultinomialNB()

In [36]:
clf.fit(training_data, train_label)

,"alpha alpha: float or array-like of shape (n_features,), default=1.0Additive (Laplace/Lidstone) smoothing parameter(set alpha=0 and force_alpha=True, for no smoothing).",1.0
,"force_alpha force_alpha: bool, default=TrueIf False and alpha is less than 1e-10, it will set alpha to1e-10. If True, alpha will remain unchanged. This may causenumerical errors if alpha is too close to 0... versionadded:: 1.2.. versionchanged:: 1.4 The default value of `force_alpha` changed to `True`.",True
,"fit_prior fit_prior: bool, default=TrueWhether to learn class prior probabilities or not.If false, a uniform prior will be used.",True
,"class_prior class_prior: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None


In [37]:
y_pred = clf.predict(testing_data)

In [38]:
y_pred

array([1, 1, 0, ..., 1, 1, 1], shape=(7000,))

In [39]:
from sklearn.metrics import accuracy_score

In [40]:
accuracy_score(test_label, y_pred)

0.952

In [41]:
y_pred_train = clf.predict(training_data)

In [42]:
accuracy_score(train_label,y_pred_train)

0.9593928571428572

# execute

In [43]:
txt=input('enter news')

enter news WEST PALM BEACH, Fla (Reuters) - President Donald Trump said on Thursday he believes he will be fairly treated in a special counsel investigation into Russian meddling in the U.S. presidential election, but said he did not know how long the probe would last. The federal investigation has hung over Trump’s White House since he took office almost a year ago, and some Trump allies have in recent weeks accused the team of Justice Department Special Counsel Robert Mueller of being biased against the Republican president. But in an interview with the New York Times, Trump appeared to shrug off concerns about the investigation, which was prompted by U.S. intelligence agencies’ conclusion that Russia tried to help Trump defeat Democrat Hillary Clinton by hacking and releasing embarrassing emails and disseminating propaganda. “There’s been no collusion. But I think he’s going to be fair,” Trump said in what the Times described as a 30-minute impromptu interview at his gol

In [44]:
news = clean_row(txt)

In [45]:
news_vec = vectorizer.transform([news])
news_df = pd.DataFrame(news_vec.toarray(), columns=vectorizer.get_feature_names_out())

# Predict
pred = clf.predict(news_df)

In [46]:
if pred == 0:
    print('news is correct')
else:
    print('news is false')

news is correct


In [47]:
pred

array([0])